version: '3'
services:
  config:
    image: "config"
    networks:
      - gym-home
  accounts:
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8081
      SPRING_DATASOURCE_HOST: accountsdb
      SPRING_CLOUD_CONSUL_HOST: consul
      COMMON_AUTHORIZATION_HOST: authorization
    image: "accounts"
    ports:
      - "8082:8082"
    networks:
      - gym-home
    depends_on:
      - config
    restart:
      always
  consul:
    image: "consul"
    networks:
      - gym-home
    ports:
      - "8500:8500"
  authorization:
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8081
      SPRING_DATASOURCE_HOST: authorizationdb
      SPRING_CLOUD_CONSUL_HOST: consul
      COMMON_AUTHORIZATION_HOST: authorization
    image: "authorization"
    ports:
      - "8085:8085"
    networks:
      - gym-home
    depends_on:
      - config
  web:
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8081
      SPRING_CLOUD_CONSUL_HOST: consul
      COMMON_AUTHORIZATION_ACCESSTOKENURI: http://authorization:8085/oauth/token
      COMMON_AUTHORIZATION_TOKENINFOURI: http://authorization:8085/oauth/check_token
    image: "web"
    ports:
      - "8084:8084"
    networks:
      - gym-home
    depends_on:
      - config
    restart:
      always
  accountsdb:
    environment:
      POSTGRES_DB: accounts
    image: "postgres"
    networks:
      - gym-home
  authorizationdb:
    environment:
      POSTGRES_DB: auth
    image: "postgres"
    networks:
      - gym-home
networks:
  gym-home:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16