version: '3'
services:
  config:
    image: "config"
    networks:
      - gym-home
  accounts:
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8081
      SPRING_DATASOURCE_HOST: accountsdb
      COMMON_EUREKA_HOST: eureka
      COMMON_AUTHORIZATION_HOST: 0.0.0.0
    image: "accounts"
    networks:
      - gym-home
    depends_on:
      - config
  eureka:
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8081
    image: "eureka"
    networks:
      - gym-home
    depends_on:
      - config
  authorization:
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8081
      SPRING_DATASOURCE_HOST: authorizationdb
      COMMON_EUREKA_HOST: eureka
    image: "authorization"
    ports:
      - "8085:8085"
    networks:
      - gym-home
    depends_on:
      - config
  accountsdb:
    environment:
      POSTGRES_DB: accounts
    image: "postgres"
    networks:
      - gym-home
  authorizationdb:
    environment:
      POSTGRES_DB: auth
    image: "postgres"
    networks:
      - gym-home
networks:
  gym-home:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16