version: '3'
services:
  config:
    image: "config"
    networks:
      - gym-home
  accounts:
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8081
      SPRING_DATASOURCE_HOST: accountsdb
      SPRING_CLOUD_CONSUL_HOST: consul
      COMMON_AUTHORIZATION_HOST: authorization
      LOGGING_LEVEL_ROOT: error
    image: "accounts"
    ports:
    - "8082:8082"
    networks:
    - gym-home
    depends_on:
    - config
  exercises-service:
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8081
      ACTIVE_PROFILE: dc
    image: "exercises"
    networks:
      - gym-home
    ports:
      - "8086:8086"
    depends_on:
      - config
    restart:
      always
  consul:
    image: "consul"
    command: "agent -log-level err -dev -client 0.0.0.0"
    networks:
      - gym-home
    ports:
      - "8500:8500"
  authorization:
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8081
      SPRING_CLOUD_CONSUL_HOST: consul
      COMMON_AUTHORIZATION_HOST: authorization
      LOGGING_LEVEL_ROOT: error
    image: "authorization"
    ports:
      - "8085:8085"
    networks:
      - gym-home
    depends_on:
      - config
  web:
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8081
      SPRING_CLOUD_CONSUL_HOST: consul
      COMMON_AUTHORIZATION_ACCESSTOKENURI: http://authorization:8085/oauth/token
      COMMON_AUTHORIZATION_TOKENINFOURI: http://authorization:8085/oauth/check_token
      LOGGING_LEVEL_ROOT: error
    image: "web"
    ports:
      - "8084:8084"
    networks:
      - gym-home
    depends_on:
      - config
    restart:
      always
  accountsdb:
    environment:
      POSTGRES_DB: accounts
    image: "postgres"
    networks:
      - gym-home
networks:
  gym-home:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16