version: '3'
services:
  config:
    image: "config"
    ports:
     - "8081"
    networks:
      - gym-home
  accounts:
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8081
      SPRING_DATASOURCE_HOST: db
      COMMON_EUREKA_HOST: eureka
    image: "accounts"
    ports:
      - "8082"
    networks:
      - gym-home
    depends_on:
      - config
  eureka:
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8081
    image: "eureka"
    ports:
      - "8083"
    networks:
      - gym-home
    depends_on:
      - config
  db:
    environment:
      POSTGRES_DB: accounts
    image: "postgres"
    networks:
      - gym-home
networks:
  gym-home:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16