version: '3'
services:
  config:
    image: "config"
    ports:
     - "8081"
    networks:
      - gym-home
  accounts:
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8081
      SPRING_DATASOURCE_HOST: db
    image: "accounts"
    ports:
      - "8082"
    networks:
      - gym-home
    depends_on:
      - config
  db:
    image: "postgres"
    networks:
      - gym-home
networks:
  gym-home:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16